version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres

  pinger:
    build: ./pinger
    container_name: pinger
    env_file: .env
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  broker:
    build: ./broker
    container_name: broker
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - backend
      - frontend

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    env_file: .env
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: